align: cleanup in member related methods inside Call
GetStream/stream-video-flutter pull request #509
Opened 2023-10-26 12:23 UTC by Brazol

2023-10-26 21:28 UTC, kanat approved these changes
LGTM

2023-10-27 08:47 UTC, deven98 requested changes
'removeMembers' -> 'updateCallMembers'

2023-10-27 08:48 UTC, deven98 requested changes
Maybe change to 'addMembers'?

2023-11-01 13:23 UTC, deven98 approved these changes
LGTM

2023-11-01 13:24 UTC, merged